### ISSUE TITLE
how hard is it to do injection

### ISSUE THREAD

**Issue by TechDudie** [Hardwaregore/Manager#3]
not very hard
if you used a proper programming language, easy peasy to prevent but... im sorry 
you CANT SUX 2BU

**Comment by TechDudie** [comment]
and also cant i login as mgr no password and
```SQL
USE `MGR`
SELECT * FROM `users`
SELECT * FROM `root_passwds`
```

**Comment by Hardwaregore** [comment]
ST🤬U
